import type { DashboardIconName } from './Icon';

// Список иконок значением, а не только типом: редактору навигации нужно
// показать их в выпадающем списке, а тип в рантайме не существует.
// Порядок алфавитный — по нему и ищут глазами.
export const ICON_NAMES: readonly DashboardIconName[] = [
  'adobe-illustrator',
  'arrow-left-01-sharp',
  'arrow-left-03-round',
  'arrow-right-01-sharp',
  'arrow-right-02-round',
  'cancel-01',
  'chevron-down',
  'chevron-down-small',
  'chevron-up',
  'colors',
  'copy-01',
  'credit-card',
  'crowdfunding',
  'download-04',
  'figma',
  'file-02',
  'floppy-disk',
  'google-drive',
  'image-02',
  'java-script',
  'jpg-02',
  'layout-table-02',
  'motion-02',
  'mp4-02',
  'nano-technology',
  'pdf-02',
  'pencil',
  'pie-chart-square',
  'png-02',
  'ppt-02',
  'presentation-07',
  'screen-add-to-home',
  'scroll-select',
  'star-circle',
  'star-square',
  'svg-02',
  'text-creation',
  'view',
  'view-off',
  'voice-id',
];
